### PR TITLE
refactor repetitive code and removed extra semicolons in manage.js

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by jacurtis — APPROVED** [review]
Good work. I really like this.

**Comment by jacurtis** [comment]
Thanks for doing this. I actually thought during the video about extracting this out into a function. But didn't do it. This is nice and clean. Thanks for the PR.

**Comment by ghost** [comment]
No problem man, that code did kinda bug me while watching the video.

Quick question and/or suggestion though. Did all of the pull requests you received lately follow your preferred coding style? Like 2-space indents for HTML and JS and 4 space indents in PHP? You might want to commit an .editorconfig file into the project for that if it comes up.

You could also set up eslint with a config that *shouts* at you for using semicolons in JS and enforce other rules.

**Edit:** Seems like you already replied to my Youtube comment too.

**Comment by jacurtis** [comment]
I am not very particular about spacing, but It wouldnt hurt to setup a `.editorconfig` and i might do that just to keep things clean.
Yep, i also saw your comment on YouTube about ESLint. Need to see if I have that or not. I don't think i do, i just have the plain JSLinter.

**Pull request merged**
