### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by carusogabriel**
Simple one: just changed the `validate` methods to `validateWith`, to avoid use the `$request` variable repeatedly

Also use the [`@forelse` blade directive](https://laravel.com/docs/5.4/blade#loops) in the `show.blade.php` user's file

### CODE REVIEW

**Comment by Bogdanchis** [comment]
Using validateWith in my case is not really working.

```
        // Validate the Create Permission form
        $this->validateWith([
            'display_name'  => 'required|max:255',
            'name'          => 'required|max:255|alphadash|unique:permissions,name',
            'description'   => 'sometimes|max:255'
        ],
        [
            'display_name.required' => 'The Name field is required.',
            'display_name.max'      => 'The Name field must be shorther than 255 characters.',
            'name.required'         => 'The Slug field is required.',
            'name.max'              => 'The Slug field must be shorther than 255 characters.',
            'name.unique'           => 'The Slug field must be uniqure.',
            'description.max'       => 'The Description field must be shorther than 255 characters.',
        
        ]);
```

**Comment by carusogabriel** [comment]
@Bogdanchis That’s because the second argument in `validateWith` is the request. This method is for comum uses, that doesn’t use custom messages. Check out [documentation](https://laravel.com/api/5.4/Illuminate/Foundation/Validation/ValidatesRequests.html#method_validateWith)!

:+1:

**Comment by roni-estein** [comment]
Thanks for the idea, I never looked at validateWith :) you have a spelling mistake in your name.unique message. 
uniqure -> unique

**Review by jacurtis — APPROVED** [review]
Looks good

**Review by jacurtis — COMMENTED** [review]
I like it. Makes it more dynamic.Thanks!

**Review by jacurtis — APPROVED** [review]
I like it. Makes it more dynamic.Thanks!

**Review by jacurtis — APPROVED** [review]

**Pull request merged**
