### PR TITLE
Ignore compiled files

### PR DESCRIPTION
**Pull request by bouasavanhhop**

### CODE REVIEW

**Comment by mario-fehr** [comment]
Why?

**Comment by bouasavanhhop** [comment]
To reduce the number of files that we need to track for the change. The forkers/cloners can always run `npm run dev` to recompile them again on their local environment.

**Comment by ghost** [comment]
Because we always use laravel-mix to build the files anyway.

**Comment by jacurtis** [comment]
Hmm... have to think about this. I already get emails 2-5 times a week asking "I downloaded your code from GitHub and it doesn't work" and then I have to explain that you need to run migrations, duplicate the .env file with your own data, etc. 

Ill leave this open while I decide. Thanks for contributing though.

**Comment by ghost** [comment]
@jacurtis To be fair, if they're using Laravel they should know this or at least try to research why this is.

Here's a suggestion, add a `README.md` and add setup instructions at the very top of it, right after the first heading.

Something like this (this is from one of mine):

## Setup

- Start your local server. (Laravel Homestead, XAMPP/WAMP/MAMP, etc.)
- `yarn install` or `npm install` (Yarn recommended)
- `yarn run dev` or `npm run dev`
- `composer install`
- configure `.env` file based on `.env.example`,
- configure database
- `php artisan key:generate`
- `php artisan migrate --seed`

You could also add a short explanation addressing those problems in the next video you record.

Should you merge this pull request, just know that it's not your responsibility to spoonfeed the viewers and answer every single email about why files are missing. We're lucky enough that you give us these tutorials for free.

**Comment by jacurtis** [comment]
I do like the idea that @raniesantos gives about adding the information to the `Readme.md` file. I think i will definitely do that.

I am going to keep the compiled CSS/JS files in the repo however. The reason really has nothing to do with beginners, and more to do with traditional workflow. You generally would track your CSS/JS files in the source code repo (at least I always have). That way when I push it to a production server I don't need to pull in all of the NPM dependencies that _Laravel Mix_ has just so I can run a compile on the server. I would prefer to keep all that stuff off the server anyway. They are kept as DevDependencies in the `package.json` for a reason and the server really doesn't need any of those files. Plus Laravel Mix requires some global installs of a few things (like SASS) which I would then need to install onto a cloud server in order to run a compile on the server to finish deployment.

There are literally hundreds of NPM dependencies that we could avoid installing on the server if we do the compiles locally and store them in the repo (because we would also need to install vue, axios, lodash, etc to complete the compile). I have always compiled locally and then when you push to productions, staging, etc the server is instantly available because the assets have already been compiled and processed. I think it is just a better workflow. I also am not used to running a compile after doing a repo pull. Generally I would use the compiled assets that come from the repo unless I decide to make changes to them. 

So I am just going to continue managing them this way. However, I will take some time soon to get a `Readme.md` file built, and add the suggestions for newcomers in there.

**Pull request closed without merging**
